######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 19 21:35:15 2009
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += /home/rich/src/project-silk/webslicer2/. .
QT += webkit

# Input
HEADERS += slicewidget.h slicegraphicswidget.h
SOURCES += main.cpp slicewidget.cpp slicegraphicswidget.cpp
