#!/usr/bin/env python

import os

kdedirs = ("/home/sebas/kdesvn/install/share/",
	   "/home/sebas/.kde4/share/")

dirs = ("applnk/selkie",
	"applnk/silk",
	"applnk/silk-*",
	"applnk/selkie-*",
	"apps/silk-*",
	"apps/selkie-*",
	"applications/kde4/selkie"
	"applications/kde4/selkie-*",
	"applications/kde4/silk",
	"applications/kde4/silk-*",
	"kde4/services/selkie",
	"kde4/services/selkie-*",
	"kde4/services/silk",
	"kde4/services/silk-*",
	"apps/selkie",
	"apps/silk",
	"applications/kde4/silk-webapp-*",
	"kde4/services/silk-webapp-*")

for kd in kdedirs:
	for d in dirs:
		cmd = "rm -rf %s%s" % (kd, d)
		print cmd
		os.system(cmd)

os.system("kbuildsycoca4")
