######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 20 14:47:35 2009
######################################################################

TEMPLATE = app
TARGET = googlesearch
DEPENDPATH += .
INCLUDEPATH += /home/rich/src/project-silk/search/. . /usr/local/kde4/include
LIBS += -L/usr/local/kde4/lib -lqjson

QT += network

# Input
HEADERS += googlesearch.h mainwindow.h
SOURCES += googlesearch.cpp main.cpp mainwindow.cpp
