######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 18 15:50:28 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += webkit

# Input
HEADERS += slicer.h slicertest.h
SOURCES += main.cpp slicer.cpp slicertest.cpp
